name: Publish docs (ensure LFS blobs) to master/docs

on:
  push:
    branches:
      - master

jobs:
  publish-docs:
    # Evita que el job corra si el actor es el bot que hizo el push
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Pull git-lfs objects
        run: |
          git lfs pull

      - name: Debug: list docs contents
        run: |
          echo "---- docs/ ----"
          ls -la docs || true
          echo "---- docs/Build ----"
          ls -la docs/Build || true

      - name: Commit real files into master/docs if changed
        env:
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: |
          # Config user
          git config user.name "$GIT_COMMITTER_NAME"
          git config user.email "$GIT_COMMITTER_EMAIL"

          # Aseguramos que los archivos del working tree (descargados por git-lfs) sean añadidos
          git add docs

          # Solo commit/push si hay cambios
          if ! git diff --cached --quiet; then
            git commit -m "ci: update docs (ensure LFS blobs present)"
            git push origin HEAD:master
          else
            echo "No hay cambios para commitear en docs"
          fi
